### ISSUE TITLE
Support for basePath like the serverless-domain-manager plugin 

### ISSUE THREAD

**Issue by gustavorps** [serverless-components/domain#10]
example for `serverless.foo.com/api`
```
custom:
  customDomain:
    domainName: serverless.foo.com
    stage: ci
    basePath: api
    certificateName: '*.foo.com'
    createRoute53Record: true
    endpointType: 'regional'
    securityPolicy: tls_1_2
```
